server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
spring:
  application:
    name: service-user
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/micro?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
